import type { SiteConfig } from "@/types/config";

export const siteConfig: SiteConfig = {
  studio: {
    name: "Flacko Locko Records",
    tagline: "Профессиональная студия звукозаписи",
    description:
      "Flacko Locko Records — Мы профессиональная студия звукозаписи в Краснодаре, делаем всё- от битов, до сведения и мастеринга, на уровне чартов.",
    logo: "/images/logo.png",
    address: {
      street: "ул. Ставропольская, 107/10",
      city: "Краснодар",
      metro: "Карасунский округ",
    },
    location: {
      coordinates: [39.020625, 45.024109] as [number, number], // [longitude, latitude]
      zoom: 18,
    },
    contact: {
      phones: ["+7 (989) 810-30-30", "+7 (918) 651-85-14"],
      email: "flackolockorec@gmail.com",
      url: "https://t.me/g1owalker",
      workingHours: {
        weekdays: "Пн-Пт: 10:00 - 23:00",
        weekends: "Сб-Вс: 12:00 - 23:00",
      },
    },
    socialMedia: {
      vk: "https://vk.com/flackolockorecords",
      soundcloud: "",
      telegram: "",
      spotify: "",
      yandexMusic: "",
      appleMusic: "",
    },
    keywords: [
      "студия звукозаписи",
      "Краснодар",
      "запись вокала",
      "сведение",
      "мастеринг",
      "аранжировка",
      "музыка",
      "Flacko Locko Records",
      "Студия звукозаписи Краснодар",
      "студия звукозаписи",
      "звукозапись",
      "записать песню Краснодар",
      "записать вокал",
      "запись вокала",
      "вокал",
      "сведение и мастеринг",
      "написание аранжировки",
      "написание битов",
      "бит на заказ",
      "трек на заказ",
      "трек под ключ Краснодар",
      "трек под ключ",
      "уроки по гитаре",
      "уроки вокала",
      "обработка звука",
      "курсы по сведению",
      "обучение сведению",
      "студия звукозаписи Flacko Locko Records",
      "запись гитары",
      "мастеринг",
      "сведение",
      "звукорежиссёр",
      "подарочный сертификат",
      "создать песню",
      "трек в стиле",
      "обработка голоса",
      "записать песню",
      "запись книги",
      "запись рекламы",
      "озвучка видео",
      "озвучить видео",
      "Записать Песню",
      "Студия Звукозаписи",
      "Звукозапись",
      "Сведение Мастеринг",
      "Подарочный Сертификат",
      "Аранжировка",
      "Сведение",
      "Мастеринг",
      "Звукорежиссёр",
      "Битмейкер",
      "Битмейкинг",
      "Студия",
      "Пение",
      "Трек",
      "Бит В Стиле",
      "Исполнитель",
      "Артист",
      "Реп",
      "Репер",
      "Музыкант",
      "Музыка",
      "FL Studio",
      "Чарты",
      "Сведение На Дистанции",
      "Трек В Стиле",
      "Гострайтинг",
      "Обложка Для Трека",
      "Озвучка",
      "Запись Рекламы",
      "Запись Диктора",
      "Запись Книги",
      "Записать Звук",
      "Обработка Вокала",
      "Обработать Голос",
      "Голос",
      "Обработка Голоса",
      "Обработать Вокал",
      "Студия Для Записи",
      "Звукозаписывающая Студия",
      "Студия Краснодар",
      "Звукозапись Краснодар",
      "Записать Песню Недорого",
      "Недорого",
      "Доступно",
      "Качественно",
      "Быстро",
    ],
  },

  hero: {
    title: {
      main: "Профессиональная студия",
      highlight: "звукозаписи",
    },
    subtitle: "Создаем музыку мирового уровня в Краснодаре. Запись, сведение, мастеринг — все для вашего успеха в музыкальной индустрии.",
    buttons: {
      primary: "Записаться",
      secondary: "Наши работы",
    },
    features: [
      {
        icon: "Music",
        title: "Профессиональное оборудование",
        description: "Студийные микрофоны, мониторы и оборудование высокого класса",
      },
      {
        icon: "Headphones",
        title: "Опытные инженеры",
        description: "Более 8 лет в индустрии",
      },
      {
        icon: "Star",
        title: "Гарантия качества",
        description: "Бесплатные 3 правки",
      },
    ],
  },

  services: [
    {
      id: "vocal-recording",
      name: "Запись вокала",
      description: "Профессиональная запись вокала в акустически обработанной студии.",
      price: { from: 1000, currency: "₽" },
      icon: "Mic",
      features: [
        "Акустически обработанная комната",
        "Микрофоны Neumann TLM 102",
        "Наушники Beyerdynamic DT 770 PRO X",
        "Звуковая карта UAD Apollo Solo",
        "Мониторинг на ADAM A7X",
      ],
    },
    {
      id: "instrument-recording",
      name: "Запись инструментов",
      description: "Качественная запись любых музыкальных инструментов: электро и акустические гитары, бас-гитара, клавишные.",
      price: { from: 1000, currency: "₽" },
      icon: "Guitar",
    },
    {
      id: "guitar-lessons",
      name: "Обучение игре на гитаре",
      description:
        "Индивидуальные уроки игры на гитаре для взрослых и детей от 7 лет. Есть музыкальное образование и сертификат «Академия наставников: гитарная революция».",
      price: { from: 1000, currency: "₽" },
      icon: "Guitar",
      features: [
        "Обучение взрослых и детей с 7 лет",
        "Музыкальное образование преподавателя",
        "Уникальная 3-х уровневая система обучения",
        "Метод «от простого к сложному»",
        "Наставник 1 категории",
      ],
    },
    {
      id: "vocal-lessons",
      name: "Обучение вокалу",
      description: "Профессиональные уроки вокала с постановкой голоса, работой над дыханием и развитием вокальной техники.",
      price: { from: 1000, currency: "₽" },
      icon: "Mic",
      features: [
        "Ритм и интонирование",
        "Постановка голоса «на опору»",
        "Вокальные атаки",
        "Техника пения сложных гласных",
        "Правильное дыхание",
        "Развитие грудного регистра",
        "Простейшие мелизмы",
        "Работа с низкими нотами",
        "Вокальная артикуляция",
        "Освоение фальцета",
      ],
    },
    {
      id: "mastering",
      name: "Мастеринг",
      description: "Финальная обработка трека для всех платформ. Оптимизация громкости, динамики и частотного баланса для стриминговых сервисов.",
      price: { from: 2000, currency: "₽" },
      icon: "Sparkles",
      features: ["Мастеринг для стриминга", "Анализ LUFS и динамического диапазона", "Несколько версий для разных платформ"],
    },
    {
      id: "mixing",
      name: "Сведение",
      description: "Профессиональное сведение ваших треков. Балансировка инструментов, обработка эффектами, создание глубины и пространства.",
      price: { from: 6500, currency: "₽" },
      icon: "Sliders",
      features: ["Работа в FL STUDIO 24", "Плагины Waves, Universal Audio"],
    },
    {
      id: "arrangement",
      name: "Аранжировка",
      description: "Создание полноценной аранжировки из вашей идеи. Добавление инструментов, гармоний, ритмических партий и оркестровки.",
      price: { from: 10000, currency: "₽" },
      icon: "FileMusic",
      features: ["Работа с живыми инструментами", "MIDI-программирование", "Современные и классические стили"],
    },
    {
      id: "mixing-mastering-courses",
      name: "Курсы по сведению и мастерингу",
      description: "Обучение работе в DAW программах, изучение VST плагинов, поэтапное обучение сведению инструментала и вокала, мастеринг.",
      price: { from: 20000, currency: "₽" },
      icon: "GraduationCap",
      features: [
        "Обучение работе в DAW программах",
        "Изучение VST плагинов и их применения",
        "Поэтапное обучение сведению",
        "Обработка инструментала (аранжировки)",
        "Обработка вокала",
        "Основы мастеринга",
        "Практические занятия",
      ],
    },
    {
      id: "production",
      name: "Продакшн",
      description: "Полный цикл создания трека от идеи до готового релиза. Композиция, аранжировка, запись, сведение, мастеринг.",
      price: { from: 30000, currency: "₽" },
      icon: "Music",
      features: ["Полный цикл производства", "Работа с артистом", "Креативная поддержка", "Готовый к релизу результат"],
    },
  ],

  equipment: [
    {
      category: "Микрофоны",
      items: ["Neumann TLM 102"],
    },
    {
      category: "Звуковая карта",
      items: ["UAD Apollo Solo"],
    },
    {
      category: "Мониторы",
      items: ["ADAM A7X"],
    },
    {
      category: "Наушники",
      items: ["Beyerdynamic DT 770 PRO X"],
    },
    {
      category: "MIDI-контроллеры",
      items: ["NEKTAR impact LX25+"],
    },
    {
      category: "Синтезаторы",
      items: ["YAMAHA PSR E463"],
    },
    {
      category: "DAW и программное обеспечение",
      items: ["FL STUDIO 24", "Плагины Waves", "Universal Audio"],
    },
  ],

  portfolio: [
    {
      id: "track-1",
      title: "Jukebox joints",
      artist: "INMYWHITEE",
      genre: "Rap/Hip-Hop",
      services: ["Запись вокала", "Аранжировка", "Сведение", "Мастеринг"],
      imageUrl: "/images/portfolio/track-1.png",
      releaseDate: "May 23, 2025",
      audioUrl: "https://music.yandex.ru/album/36692569?utm_source=web&utm_medium=copy_link",
    },
    {
      id: "track-2",
      title: "FLEX & FURIOUS",
      artist: "INMYWHITEE, MUZZLE FLA$H",
      genre: "Rap/Hip-Hop",
      services: ["Запись вокала", "Аранжировка", "Сведение", "Мастеринг"],
      imageUrl: "/images/portfolio/track-2.png",
      releaseDate: "Feb 28, 2025",
      audioUrl: "https://music.yandex.ru/album/35541801?utm_source=web&utm_medium=copy_link",
    },
    {
      id: "track-3",
      title: "ВСЕ И СРАЗУ)",
      artist: "OSPA",
      genre: "Rap/Hip-Hop",
      services: ["Сведение", "Мастеринг"],
      imageUrl: "/images/portfolio/track-3.png",
      releaseDate: "Aug. 9, 2024",
      audioUrl: "https://music.yandex.ru/album/32651996?utm_source=web&utm_medium=copy_link",
    },
    {
      id: "track-4",
      title: "Expensive Tearz",
      artist: "sugakkilla",
      genre: "Rap/Hip-Hop",
      services: ["Запись вокала", "Сведение", "Мастеринг"],
      imageUrl: "/images/portfolio/track-4.jpg",
      releaseDate: "Aug. 22, 2025",
      audioUrl: "https://music.yandex.ru/album/36529191?utm_source=web&utm_medium=copy_link",
    },
    {
      id: "track-5",
      title: "TRAP EXPERT",
      artist: "SAINT G SAVAGE",
      genre: "Rap/Hip-Hop",
      services: ["Запись вокала", "Сведение", "Мастеринг"],
      imageUrl: "/images/portfolio/track-5.jpg",
      releaseDate: "Sep. 5, 2025",
      audioUrl: "https://music.yandex.ru/album/38041521?utm_source=web&utm_medium=copy_link",
    },
    {
      id: "track-6",
      title: "ADPS",
      artist: "MUZZLE FLA$H",
      genre: "Rap/Hip-Hop",
      services: ["Запись вокала", "Аранжировка", "Сведение", "Мастеринг"],
      imageUrl: "/images/portfolio/track-6.jpg",
      releaseDate: "Mar. 28, 2025",
      audioUrl: "https://music.yandex.ru/album/35873987?utm_source=web&utm_medium=copy_link",
    },
  ],

  gallery: [
    {
      id: "studio-1",
      title: "Главная студия",
      description: "Основная комната для записи и обработки звкука",
      imageUrl: "/images/studio/studio-1.jpg",
    },
    {
      id: "studio-2",
      title: "",
      description: "",
      imageUrl: "/images/studio/studio-2.jpg",
    },
    {
      id: "studio-3",
      title: "",
      description: "",
      imageUrl: "/images/studio/studio-3.jpg",
    },
    {
      id: "studio-4",
      title: "",
      description: "",
      imageUrl: "/images/studio/studio-4.png",
    },
  ],

  team: [
    {
      id: "g1owalker",
      name: "Юрий Баранов",
      role: "Звукоинженер, Продюссер",
      experience: "8 лет",
      photo: "/images/team/yura.jpg",
      bio: "Звукоинженер с огромным опытом, поможет вам добиться желаемого результата, работет с любыми музыкальными жанрами.",
    },
    {
      id: "INMYWHITEE",
      name: "Евгений Смаилов",
      role: "Звукоинженер, Продюсер",
      experience: "8 лет",
      photo: "/images/team/evgeniy.jpg",
      bio: "Артист, продюсер и звукоинжер с опытом работы в различных жанрах. Специализируется на Хип-хоп, Поп, R&B и электронной музыке.",
    },
  ],

  stats: [
    { value: "500+", label: "Записанных треков" },
    { value: "8+", label: "Лет опыта" },
    { value: "200+", label: "Довольных клиентов" },
    { value: "24/7", label: "Поддержка" },
  ],

  sections: {
    about: {
      title: "О нашей студии",
      additionalDescription:
        "Мы работаем с артистами всех жанров и уровней — от начинающих музыкантов до известных исполнителей. Наша цель — помочь каждому клиенту реализовать свое творческое видение на высшем уровне.",
      equipmentTitle: "Профессиональное оборудование",
      learnMoreButton: "Узнать больше",
    },
    services: {
      title: "Наши услуги",
      subtitle: "Полный спектр услуг для создания профессиональной музыки",
    },
    gallery: {
      title: "Студия изнутри",
      subtitle: "Посмотрите на наше профессиональное оборудование и рабочий процесс",
    },
    portfolio: {
      title: "Наши работы",
      subtitle: "Примеры проектов, над которыми мы работали",
      listenButton: "Слушать",
      detailsButton: "Подробнее",
    },
    team: {
      title: "Наша команда",
      subtitle: "Профессионалы с многолетним опытом в музыкальной индустрии",
    },
    reviews: {
      title: "Отзывы клиентов",
      subtitle: "Что говорят о нас наши клиенты",
    },
    contact: {
      title: "Связаться с нами",
      subtitle: "Готовы начать работу над вашим проектом? Свяжитесь с нами!",
      telegram: {
        title: "Напишите нам в Telegram",
        description: "Самый быстрый способ связаться с нами и обсудить ваш проект. Мы ответим в течение нескольких минут!",
        buttonText: "Написать в Telegram",
      },
      info: {
        addressTitle: "Адрес студии",
        phoneTitle: "Телефон",
        emailTitle: "Email",
        workingHoursTitle: "Режим работы",
      },
      mapTitle: "Как нас найти",
    },
    footer: {
      servicesTitle: "Услуги",
      contactsTitle: "Контакты",
      socialTitle: "Социальные сети",
      copyright: "All rights reserved",
    },
  },
};
